name: avikam_print_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.6.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  open_filex: ^4.5.0
  path_provider: ^2.1.4
  printing: ^5.13.2
  bluetooth_print_plus: ^2.1.6
  pdfx: ^2.6.0
  pdf_image_renderer: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
